const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
let scenarios,side,scenario,step=0,pending=null,history={mail:[],wa:[],teams:[]};
const names={mail:'MAIL',wa:'WHATISUP',teams:'MYCORESOFT TEAMS'};
const clean=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function show(id){['landing','reveal','journeys','work','end'].forEach(x=>$('#'+x).classList.toggle('hidden',x!==id))}
function reset(){scenario=null;step=0;pending=null;history={mail:[],wa:[],teams:[]};$('#attention').classList.add('hidden');$('#decision').classList.add('hidden')}
function channel(c){$$('.channel').forEach(x=>x.classList.toggle('active',x.id===c));$$('[data-channel]').forEach(x=>x.classList.toggle('active',x.dataset.channel===c))}
function render(){
 $('#mailThread').innerHTML=history.mail.map(m=>`<div class="msg ${m.you?'you':''}"><div class="meta">${m.you?'YOU':side==='client'?'AGENCY':'CLIENT'}</div>${clean(m.text)}</div>`).join('');
 $('#waThread').innerHTML=history.wa.map(m=>`<div class="bubble ${m.you?'you':''}">${clean(m.text)}</div>`).join('');
 $('#teamThread').innerHTML=history.teams.map(m=>`<div class="post"><b>${clean(m.name)}</b><div>${clean(m.text)}</div></div>`).join('');
 ['mailThread','waThread','teamThread'].forEach(id=>$('#'+id).scrollTop=999999)
}
function incoming(s){channel(s[0]);if(s[0]==='mail')history.mail.push({text:s[1]});else if(s[0]==='wa')history.wa.push({text:s[1]});else (s[2]||[]).forEach(p=>history.teams.push({name:p[0],text:p[1]}));render()}
function sent(c,text){if(c==='mail')history.mail.push({text,you:true});else if(c==='wa')history.wa.push({text,you:true});else history.teams.push({name:'YOU',text});render()}
function typeAndSend(c,text){return new Promise(ok=>{let el=c==='mail'?$('#mailComposer'):c==='wa'?$('#waComposer'):$('.channel.active .composer');el.classList.remove('hidden');el.textContent=c==='mail'?`Typing: ${text}`:`Typing: ${text}`;setTimeout(()=>{sent(c,text);el.textContent=c==='mail'?'':c==='wa'?'Message':'Start a post';ok()},1050)})}
function branchReply(s,i){let choice=s[3][i];let role=side==='client'?'client':'agency';if(role==='client')return [`I want to respond to that properly rather than give you a vague steer. ${choice} What I need from you is a recommendation that helps us make the decision, not another round of ambiguity.`,`Let me be clear about the direction: ${choice} I know that changes the conversation slightly, so please build the next step around that rather than treating it as a brand-new brief.`,`I'll take that route. ${choice} If there is a trade-off, show it to me plainly so I can make the call internally.`][i];return [`I think we should approach this deliberately. ${choice} Before we create more work, let's make sure this solves the actual client problem.`,`I'll take that route. ${choice} Let's document the implication so account, strategy and creative are all solving the same thing.`,`That's the direction I'd take. ${choice} Let's be explicit about the trade-off rather than quietly absorbing it into the next round.`][i]}
function branchIncoming(s,i){let base=s[1];let reactions=side==='client'?['They reply: “That gives us something useful to work with. Let me take this internally.”','They reply: “Okay. That is more specific than the original brief. Let’s build from there.”','They reply: “Fair. We can work with that, but I may need to push this internally.”']:['The client replies: “Okay. That is a much clearer way of putting it.”','The client replies: “I can take that internally. Give me a strong recommendation, not ten options.”','The client replies: “Fair. Just remember we need something we can defend internally.”'];return base+'\n\n'+reactions[i]}
function notify(s,after){channel(s[0]);$('#attentionChannel').textContent=names[s[0]];$('#attentionMessage').textContent=s[0]==='mail'?'A new email just arrived.':s[0]==='wa'?'New message on WhatisUp.':'Someone posted in Teams.';$('#attention').classList.remove('hidden');pending=()=>{incoming(s);after()}}
function decide(s){$('#decisionPrompt').textContent=s[2];$('#choiceButtons').innerHTML=s[3].map((x,i)=>`<button class="choice" data-i="${i}">${clean(x)}</button>`).join('');$('#decision').classList.remove('hidden')}
async function choose(i){let s=scenario.steps[step];$('#decision').classList.add('hidden');let reply=branchReply(s,i);await typeAndSend(s[0],reply);step++;if(step<scenario.steps.length){let next=scenario.steps[step];next=[next[0],branchIncoming(next,i),next[2],next[3],next[4]];setTimeout(()=>notify(next,()=>decide(next)),1150)}else setTimeout(()=>finish(i),1400)}
function finish(i){$('#endTitle').textContent=scenario.end||'You made it through.';$('#endCopy').textContent='The workday ends here. Your choices mattered. The next experience does not have to.';show('end');setTimeout(()=>{show('journeys');renderJourneys()},2200)}
function renderJourneys(){$('#roleLabel').textContent=side==='client'?'CLIENT':'AGENCY';$('#journeyCards').innerHTML=scenarios[side].map((s,i)=>`<button class="card" data-id="${s.id}"><span class="eyebrow">0${i+1}</span><h3>${s.title}</h3><p>${s.desc}</p></button>`).join('')}
function start(sc){reset();scenario=sc;$('#persistentRole').textContent=side==='client'?'CLIENT':'AGENCY';$('#scenarioLabel').textContent=sc.title.toUpperCase();$('#mailSubject').textContent=sc.subject;$('#waTitle').textContent='Current agency';$('#teamOrg').textContent=side==='client'?'YOUR WORKPLACE':'YOUR AGENCY';$('#teamRooms').innerHTML=(side==='client'?['#marketing','#brand','#leadership','#creative','#random']:['#account','#creative','#strategy','#production','#leadership','#random']).map(x=>`<div>${x}</div>`).join('');channel('mail');show('work');setTimeout(()=>notify(sc.steps[0],()=>decide(sc.steps[0])),500)}
$$('[data-role]').forEach(b=>b.onclick=()=>{side=b.dataset.role;$('#roleTitle').textContent=side==='agency'?"Well, you're the client now.":"Well, you're the agency now.";$('#roleCopy').textContent=side==='agency'?'Try not to make it personal.':'Good luck with the brief.';show('reveal')});
$('#startJourneys').onclick=()=>{renderJourneys();show('journeys')};
$('#journeyCards').onclick=e=>{let b=e.target.closest('[data-id]');if(b)start(scenarios[side].find(s=>s.id===b.dataset.id))};
$('#openAttention').onclick=()=>{let f=pending;pending=null;$('#attention').classList.add('hidden');if(f)f()};
$('#choiceButtons').onclick=e=>{let b=e.target.closest('.choice');if(b)choose(+b.dataset.i)};
$$('[data-channel]').forEach(b=>b.onclick=()=>channel(b.dataset.channel));
$('#another').onclick=()=>{renderJourneys();show('journeys')};
$('#workEscape').onclick=()=>{reset();show('landing')};
$$('[data-escape]').forEach(b=>b.onclick=()=>{reset();show('landing')});
fetch('scenarios.json').then(r=>r.json()).then(x=>scenarios=x);
